table Available_Dates {
  id integer [pk, not null]
  venue_id integer [not null]
  available_date text [not null]

  indexes {
    (venue_id, available_date) [name: 'unique_date', unique]
  }
}

table Events {
  id integer [pk, not null]
  venue_id integer [not null]
  organizer_id integer [not null]
  name text [not null]
  description text
  start_date text [not null]
  end_date text [not null]
  invite_only integer [default: 0]
  created_at text [default: `CURRENT_TIMESTAMP`]
}

table Images {
  id integer [pk, not null]
  event_id integer
  venue_id integer
  thumbnail integer [default: false]
  image_url text [not null]
  created_at text [default: `CURRENT_TIMESTAMP`]

  indexes {
    (venue_id, thumbnail) [name: 'unique_thumbnail', unique]
  }
}

table Invitations {
  id integer [pk, not null]
  event_id integer [not null]
  user_id integer [not null]
  sent_date text [default: `CURRENT_TIMESTAMP`]
  status text
}

table Notifications {
  id integer [pk, not null]
  user_id integer [not null]
  event_id integer
  message text [not null]
  status text [default: 'Unread']
  created_at text [default: `CURRENT_TIMESTAMP`]
}

table Post_Likes {
  id integer [pk, not null]
  post_id integer [not null]
  user_id integer [not null]

  indexes {
    (post_id, user_id) [name: 'unique_user_like', unique]
  }
}

table Posts {
  id integer [pk, not null]
  event_id integer [not null]
  user_id integer [not null]
  content text [not null]
  like_count integer [default: 0]
  parent_post_id integer
  created_at text [default: `CURRENT_TIMESTAMP`]
}

table Tokens {
  id integer [pk, not null]
  user_id integer [not null]
  token text [not null, unique]
  created_at text [default: `CURRENT_TIMESTAMP`]
}

table Users {
  id integer [pk, not null]
  name text [not null]
  email text [not null, unique]
  last_login text [not null, default: `CURRENT_TIMESTAMP`]
  created_at text [default: `CURRENT_TIMESTAMP`]
}

table Venue_Rentals {
  id integer [pk, not null]
  user_id integer [not null]
  venue_id integer [not null]
  start_date text [not null]
  end_date text [not null]
}

table Venues {
  id integer [pk, not null]
  owner_id integer [not null]
  name text [not null]
  location text [not null]
  description text
  capacity integer
  price real
  created_at text [default: `CURRENT_TIMESTAMP`]
}

ref: Available_Dates.venue_id > Venues.id

ref: Events.venue_id > Venues.id

ref: Events.organizer_id > Users.id

ref: Images.event_id > Events.id

ref: Images.venue_id > Venues.id

ref: Invitations.event_id > Events.id

ref: Invitations.user_id > Users.id

ref: Notifications.event_id > Events.id

ref: Notifications.user_id > Users.id

ref: Post_Likes.post_id > Posts.id

ref: Post_Likes.user_id > Users.id

ref: Posts.event_id > Events.id

ref: Posts.user_id > Users.id

ref: Posts.parent_post_id - Posts.id

ref: Tokens.user_id > Users.id

ref: Venues.owner_id > Users.id

ref: Venue_Rentals.user_id > Users.id

ref: Venue_Rentals.venue_id > Venues.id