table Available_Dates {
  availability_id integer [pk, not null]
  venue_id integer [not null]
  available_date text [not null]
}

table Events {
  event_id integer [pk, not null]
  venue_id integer [not null]
  organizer_id integer [not null]
  name text [not null]
  description text
  start_date text [not null]
  end_date text [not null]
  invite_only integer [default: 0]
  created_at text [default: `CURRENT_TIMESTAMP`]
}

table Images {
  image_id integer [pk, not null]
  image_url text [not null]
  created_at text [default: `CURRENT_TIMESTAMP`]
}

table Invitations {
  invitation_id integer [pk, not null]
  event_id integer [not null]
  user_id integer [not null]
  sent_date text [default: `CURRENT_TIMESTAMP`]
  status text
}

table Notifications {
  notification_id integer [pk, not null]
  user_id integer [not null]
  event_id integer
  message text [not null]
  status text [default: 'Unread']
  created_at text [default: `CURRENT_TIMESTAMP`]
}

table Post_Likes {
  like_id integer [pk, not null]
  post_id integer [not null]
  user_id integer [not null]

  indexes {
    (post_id, user_id) [name: 'unique_post_user', unique]
  }
}

table Posts {
  post_id integer [pk, not null]
  event_id integer [not null]
  user_id integer [not null]
  content text [not null]
  like_count integer [default: 0]
  parent_post_id integer
  created_at text [default: `CURRENT_TIMESTAMP`]
}

table Tokens {
  token_id integer [pk, not null]
  user_id integer [not null]
  token text [not null, unique]
  created_at text [default: `CURRENT_TIMESTAMP`]
}

table Users {
  user_id integer [pk, not null]
  name text [not null]
  email text [not null, unique]
  password text [not null]
  created_at text [default: `CURRENT_TIMESTAMP`]
}

table Venue_Rentals {
  rental_id integer [pk, not null]
  user_id integer [not null]
  venue_id integer [not null]
  start_date text [not null]
  end_date text [not null]
}

table Venues {
  venue_id integer [pk, not null]
  owner_id integer [not null]
  name text [not null]
  location text [not null]
  description text
  capacity integer
  price real
  thumbnail_image_id integer
  created_at text [default: `CURRENT_TIMESTAMP`]
}

ref: Available_Dates.venue_id - Venues.venue_id

ref: Events.venue_id - Venues.venue_id

ref: Events.organizer_id - Users.user_id

ref: Invitations.event_id - Events.event_id

ref: Invitations.user_id - Users.user_id

ref: Notifications.user_id - Users.user_id

ref: Notifications.event_id - Events.event_id

ref: Post_Likes.post_id - Posts.post_id

ref: Post_Likes.user_id - Users.user_id

ref: Posts.event_id - Events.event_id

ref: Posts.user_id - Users.user_id

ref: Posts.parent_post_id - Posts.post_id

ref: Tokens.user_id - Users.user_id

ref: Venues.thumbnail_image_id - Images.image_id

ref: Venue_Rentals.user_id - Users.user_id

ref: Venue_Rentals.venue_id - Venues.venue_id